/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class bingcao_TestJNI */

#ifndef _Included_bingcao_TestJNI
#define _Included_bingcao_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bingcao_TestJNI
 * Method:    nativeMethod
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_bingcao_TestJNI_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
